import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google"; // Importa a fonte Inter
import "./globals.css";
import { ToastProvider } from "../context/ToastContext"; // Importa o provedor do contexto do toast
import ToastNotification from "./componentes/ToastNotification"; // Importa o componente de notificação

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Instancia a fonte Inter
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap", // Adiciona display: "swap" para melhor performance
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`} // Adiciona a variável da fonte Inter
      >
        {/* ToastProvider envolve toda a aplicação para fornecer o contexto do toast */}
        <ToastProvider>
          {children}
          {/* ToastNotification é renderizado aqui, no nível mais alto da aplicação,
              fora de qualquer contêiner que possa interferir no seu posicionamento fixo */}
          <ToastNotification />
        </ToastProvider>
      </body>
    </html>
  );
}
